# This is a basic workflow to help you get started with Actions

name: validate ElastAlert Rule

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main", "third" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # This displays in workflow
    name : ElastAlert Rule
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run installation script
        run: sudo apt-get install python3-tk

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install simple-chalk
          pip install pyyaml
          pip install cerberus
          
      # Runs a single command using the runners shell
      - name: Run a python script
        run: python runn.py
